
export const indianLanguages: { [key: string]: string } = {
  en: 'English',
  hi: 'Hindi',
  mr: 'Marathi',
  gu: 'Gujarati',
  kn: 'Kannada',
  bn: 'Bengali',
  te: 'Telugu',
  ml: 'Malayalam',
  ur: 'Urdu',
  auto: 'Auto Detect'
};

export const subjects: { [key: string]: string } = {
  'History': 'इतिहास',
  'Marathi': 'मराठी',
  'Hindi': 'हिंदी',
  'English': 'अंग्रेजी',
  'Science': 'विज्ञान',
  'Maths': 'गणित',
  'Geography': 'भूगोल',
  'Civics': 'नागरिक शास्त्र'
};

export const subjectEmojis: { [key: string]: string } = {
  'History': '🏰',
  'Marathi': '🚩',
  'Hindi': '🇮🇳',
  'English': '🅰️',
  'Science': '🧬',
  'Sci': '🧬',
  'Maths': '📐',
  'Geography': '🌍',
  'Civics': '⚖️'
};

export const digestNotes = [
  { id: 201, subject: 'ENGLISH NAVNEET DIGEST', description: 'English Balbharati Digest', url: 'https://drive.google.com/file/d/1eRAGimDlOm2vVJPP-TLAcC7R2Q-dL3PU/preview?rm=minimal' },
  { id: 202, subject: 'HINDI NAVNEET DIGEST', description: 'Hindi Lokbharati Digest', url: 'https://drive.google.com/file/d/1IOIJySYsoNgTL7e5it2Q9ySEgl7bQRhE/preview?rm=minimal' },
  { id: 203, subject: 'MARATHI DIGEST (NOT NAVNEET)', description: 'Marathi Kumarbharati Digest', url: 'https://drive.google.com/file/d/1ezy0kf5IFbgcmO8QgAWafapj4EeTx0p7/preview?rm=minimal' },
  { id: 204, subject: 'MATHS 1 DIGEST (Not Navneet)', description: 'Mathematics Part-I Digest', url: 'https://drive.google.com/file/d/1FlGZLPEh8sqO-oopmYKQNjMP2xINzL5E/preview?rm=minimal' },
  { id: 205, subject: 'MATHS 2 NAVNEET DIGEST', description: 'Mathematics Part-II Digest', url: 'https://drive.google.com/file/d/1tVFLqWcAvvQj3-M_DHv_fPxZ79hvyETe/preview?rm=minimal' },
  { id: 206, subject: 'SCI 1 NAVNEET DIGEST', description: 'Science and Technology Part-1', url: 'https://drive.google.com/file/d/1rONXuWIaMJdUw7nRIo2vpQv85p-jdV11/preview?rm=minimal' },
  { id: 207, subject: 'Science-2 Digest (Not Navneet)', description: 'Science and Technology Part-2', url: 'https://drive.google.com/file/d/13PWvuYDHKNdRb_dSxU_aYkcwQTM-7IoF/preview?rm=minimal' },
  { id: 208, subject: 'HISTORY AND POLITICAL SCI NAVNEET DIGEST', description: 'History and Political Science', url: 'https://drive.google.com/file/d/1TOjaB44PV0T_IFyhaor9gDWZEZqjXZk7/preview?rm=minimal' },
  { id: 209, subject: 'Geography Digest (Not Navneet)', description: 'Geography Digest', url: 'https://drive.google.com/file/d/1QiwHaDht7KxMaGeQ9GEBsFBjF7NAmvS2/preview?rm=minimal' }
];

export const pdfNotes = [
  { id: 102, subject: 'P.T BOOK SOLUTIONS', description: 'The complete PDF of important notes related to P.T Book Solutions.', url: 'https://drive.google.com/file/d/10Ad_D5_HvHZbhfM9VuNF33z3bEOqKCjl/preview?rm=minimal' },
  { id: 103, subject: 'DEFENCE STUDIES FULL BOOK WITH SOLUTION', description: 'Complete book with solutions for Defence Studies.', url: 'https://drive.google.com/file/d/1_EBrqYFEk8W8V05fXX9wejbGvVi_cGWb/preview?rm=minimal' },
  { id: 104, subject: 'MATHS PRACTICAL FULL BOOK WITH SOLUTION', description: 'Complete practical book with solutions for Mathematics.', url: 'https://drive.google.com/file/d/1Rw32CtK2z7isqd9Wy5Sh3pDGm3FcaAU8/preview?rm=minimal' }
];

export const kavitas = [
  { id: 1, title: 'Jai Jai Maharashtra Maza', appreciation: 'Gaurav Geet praising the greatness of Maharashtra state.' },
  { id: 2, title: 'Santavani (A)', appreciation: 'Abhang by Sant Tukaram Maharaj about the importance of Varkari Sampraday.' },
  { id: 3, title: 'Santavani (B)', appreciation: 'Abhang by Sant Namdev regarding devotion.' },
  { id: 4, title: 'Ankila Mi Das Tuza', appreciation: 'Devotional poem by Sant Namdev.' },
  { id: 5, title: 'Yogi Sarvakal Sukhdata', appreciation: 'Comparing Yogi and Water (Jal) by Sant Eknath.' }
];

export const translations: { [lang: string]: { [key: string]: string } } = {
  en: {
      app_name: 'An Educational App',
      loading_msg: 'Loading...',
      ad_title: 'Advertisement',
      ad_placeholder: 'Ad Space',
      continue: 'Continue',
      pdf_viewer_title: 'Document Viewer',
      warning: 'Warning',
      pdf_warning_message: 'This material is copyright protected. Do not distribute.',
      profile_title: 'Profile',
      profile_name: 'Name',
      profile_school: 'School',
      profile_standard: 'Standard',
      back: 'Back',
      feedback_button: 'Feedback',
      dark_mode_label: 'Dark Mode',
      feedback_title: 'Send Feedback',
      feedback_placeholder: 'Describe your issue or suggestion...',
      cancel_button: 'Cancel',
      submit_button: 'Submit',
      feedback_success_title: 'Feedback Sent',
      feedback_success_msg: 'Thank you for your feedback!',
      choose_language: 'Choose Your Language',
      confirm_button: 'Confirm',
      onboarding_terms_error: 'You must agree to the terms.',
      standard_error: 'Please select a standard',
      onboarding_agree_terms: 'I AGREE TO THE TERMS & CONDITIONS',
      next: 'Next',
      get_started: 'Get Started',
      back_to_edit: 'Edit',
      registration_complete: 'Registration Complete',
      registration_success_msg: 'You are all set!',
      welcome_msg: 'Welcome back,',
      choose_mode: 'Choose Mode',
      extra_mode: 'Extra Mode',
      extra_mode_desc: 'Additional study materials & resources',
      simple_mode: 'Simple Mode',
      simple_mode_desc: 'Digests and basic notes',
      ai_translator_mode: 'AI Translator',
      ai_translator_desc: 'Translate languages instantly',
      theme_settings_title: 'Theme Settings',
      dark_mode_description: 'Toggle dark mode for a better viewing experience at night.',
      system_theme_label: 'Sync with System',
      system_theme_description: 'Automatically adjust the theme to match your device\'s system settings.',
      extra_mode_title: 'Extra Study Mode',
      purpose_1: 'This mode provides extra resources.',
      purpose_2: 'Select a Subject:',
      subject_class: 'Notes',
      simple_mode_title: 'Simple Study Mode',
      free_digest: 'Free Digests',
      free_digest_desc: 'Access full subject digests.',
      view_digest: 'View Digest',
      graded_notes: 'Graded Notes',
      graded_notes_desc: 'Notes organized by grade.',
      view_pdf_notes: 'View PDF Notes',
      download_warning: 'Downloading is disabled.',
      ai_title: 'AI Translator',
      ai_source: 'From',
      ai_target: 'To',
      ai_prompt: 'Enter text...',
      ai_output: 'Translation',
      ai_translating: 'Translating...',
      ai_translate_btn: 'Translate',
      ai_input_error: 'Input cannot be empty',
      ai_error: 'Translation error occurred.',
      ai_tts_error: 'Speech generation failed.',
      notes_title: 'Notes',
      pattern_notes: 'Pattern Notes',
      rasagran_notes: 'Rasagran Notes',
      rasagran_basics: 'Rasagran Basics',
      rasagran_text: 'Information about Rasagran...',
      lesson_qna_notes: 'Lesson Q&A',
      lesson_qna_text: 'Questions and Answers...',
      rasagran_list_title: 'Poems (Kavita)',
      content_area_warning: '⚠️ This material is in \'Photo Format\'. Copying or downloading is not possible.',
      subject_coming_soon: 'Coming Soon',
      subject_placeholder: 'Notes for this subject are being uploaded.',
      digest_select_title: 'Select Digest',
      pdf_select_title: 'Select PDF Note',
      about_us: 'About Us',
      about_app_desc: 'Gyan Sangam is a comprehensive educational application designed to make learning accessible and easier for students. It provides digital access to digests, notes, and AI-powered tools.',
      version: 'Version',
      about_simple_mode: 'Simple Mode: This mode offers direct access to standard curriculum resources like Digests and basic revision notes. Ideal for daily studies and quick references.',
      about_extra_mode: 'Extra Mode: Explore additional study materials, subject-specific deep dives, and specialized resources to enhance your understanding beyond the basics.',
      developed_by: 'Developed by',
      history_btn: 'History',
      history_title: 'Translation History',
      history_empty: 'No recent history.',
      use_this: 'Use',
      clear_history: 'Clear History',
  },
  hi: {
      app_name: 'एक शैक्षिक ऐप',
      loading_msg: 'लोड हो रहा है...',
      ad_title: 'विज्ञापन',
      ad_placeholder: 'विज्ञापन स्थान',
      continue: 'जारी रखें',
      pdf_viewer_title: 'दस्तावेज़ व्यूअर',
      warning: 'चेतावनी',
      pdf_warning_message: 'यह सामग्री कॉपीराइट सुरक्षित है। वितरित न करें।',
      profile_title: 'प्रोफ़ाइल',
      profile_name: 'नाम',
      profile_school: 'स्कूल',
      profile_standard: 'कक्षा',
      back: 'वापस',
      feedback_button: 'प्रतिक्रिया',
      dark_mode_label: 'डार्क मोड',
      feedback_title: 'प्रतिक्रिया भेजें',
      feedback_placeholder: 'अपनी समस्या या सुझाव का वर्णन करें...',
      cancel_button: 'रद्द करें',
      submit_button: 'जमा करें',
      feedback_success_title: 'प्रतिक्रिया भेजी गई',
      feedback_success_msg: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
      choose_language: 'अपनी भाषा चुनें',
      confirm_button: 'पुष्टि करें',
      onboarding_terms_error: 'आपको शर्तों से सहमत होना चाहिए।',
      standard_error: 'कृपया एक कक्षा चुनें',
      onboarding_agree_terms: 'मैं नियमों और शर्तों से सहमत हूं',
      next: 'अगला',
      get_started: 'शुरू करें',
      back_to_edit: 'संपादित करें',
      registration_complete: 'पंजीकरण पूरा हुआ',
      registration_success_msg: 'आप पूरी तरह तैयार हैं!',
      welcome_msg: 'वापसी पर स्वागत है,',
      choose_mode: 'मोड चुनें',
      extra_mode: 'एक्स्ट्रा मोड',
      extra_mode_desc: 'अतिरिक्त अध्ययन सामग्री और संसाधन',
      simple_mode: 'सरल मोड',
      simple_mode_desc: 'डायजेस्ट और बुनियादी नोट्स',
      ai_translator_mode: 'AI अनुवादक',
      ai_translator_desc: 'भाषाओं का तुरंत अनुवाद करें',
      theme_settings_title: 'थीम सेटिंग्स',
      dark_mode_description: 'रात में बेहतर देखने के अनुभव के लिए डार्क मोड टॉगल करें।',
      system_theme_label: 'सिस्टम के साथ सिंक करें',
      system_theme_description: 'अपनी डिवाइस सेटिंग्स के आधार पर थीम को स्वचालित रूप से समायोजित करें।',
      extra_mode_title: 'एक्स्ट्रा स्टडी मोड',
      purpose_1: 'यह मोड अतिरिक्त संसाधन प्रदान करता है।',
      purpose_2: 'एक विषय चुनें:',
      subject_class: 'नोट्स',
      simple_mode_title: 'सरल अध्ययन मोड',
      free_digest: 'मुफ्त डायजेस्ट',
      free_digest_desc: 'पूर्ण विषय डायजेस्ट तक पहुंचें।',
      view_digest: 'डायजेस्ट देखें',
      graded_notes: 'graded नोट्स',
      graded_notes_desc: 'ग्रेड द्वारा व्यवस्थित नोट्स।',
      view_pdf_notes: 'PDF नोट्स देखें',
      download_warning: 'डाउनलोड अक्षम है।',
      ai_title: 'AI अनुवादक',
      ai_source: 'से',
      ai_target: 'को',
      ai_prompt: 'टेक्स्ट दर्ज करें...',
      ai_output: 'अनुवाद',
      ai_translating: 'अनुवाद हो रहा है...',
      ai_translate_btn: 'अनुवाद करें',
      ai_input_error: 'इनपुट खाली नहीं हो सकता',
      ai_error: 'अनुवाद त्रुटि हुई।',
      ai_tts_error: 'वाक् निर्माण विफल रहा।',
      notes_title: 'नोट्स',
      pattern_notes: 'पैटर्न नोट्स',
      rasagran_notes: 'रसग्रहण नोट्स',
      rasagran_basics: 'रसग्रहण मूल बातें',
      rasagran_text: 'रसग्रहण के बारे में जानकारी...',
      lesson_qna_notes: 'पाठ प्रश्नोत्तर',
      lesson_qna_text: 'प्रश्न और उत्तर...',
      rasagran_list_title: 'कविताएं',
      content_area_warning: '⚠️ यह सामग्री \'फोटो प्रारूप\' में है। कॉपी करना या डाउनलोड करना संभव नहीं है।',
      subject_coming_soon: 'जल्द आ रहा है',
      subject_placeholder: 'इस विषय के लिए नोट्स अपलोड किए जा रहे हैं।',
      digest_select_title: 'डायजेस्ट चुनें',
      pdf_select_title: 'PDF नोट चुनें',
      about_us: 'हमारे बारे में',
      about_app_desc: 'ज्ञान संगम एक व्यापक शैक्षिक ऐप है जिसे छात्रों के लिए सीखने को सुलभ और आसान बनाने के लिए डिज़ाइन किया गया है। यह डायजेस्ट, नोट्स और AI-संचालित उपकरणों तक डिजिटल पहुंच प्रदान करता है।',
      version: 'संस्करण',
      about_simple_mode: 'सरल मोड: यह मोड डायजेस्ट और बुनियादी संशोधन नोट्स जैसे मानक पाठ्यक्रम संसाधनों तक सीधी पहुंच प्रदान करता है। दैनिक अध्ययन और त्वरित संदर्भ के लिए आदर्श।',
      about_extra_mode: 'एक्स्ट्रा मोड: मूल बातें से परे अपनी समझ को बढ़ाने के लिए अतिरिक्त अध्ययन सामग्री, विषय-विशिष्ट गहन जानकारी और विशेष संसाधनों का अन्वेषण करें।',
      developed_by: 'द्वारा विकसित',
      history_btn: 'इतिहास',
      history_title: 'अनुवाद इतिहास',
      history_empty: 'कोई हालिया इतिहास नहीं।',
      use_this: 'उपयोग करें',
      clear_history: 'इतिहास मिटाएं',
  },
  mr: {
      app_name: 'एक शैक्षणिक ॲप',
      loading_msg: 'लोड होत आहे...',
      ad_title: 'जाहिरात',
      ad_placeholder: 'जाहिरात जागा',
      continue: 'पुढे जा',
      pdf_viewer_title: 'कागदपत्र दर्शक',
      warning: 'चेतावणी',
      pdf_warning_message: 'हे साहित्य कॉपीराइट संरक्षित आहे. वितरित करू नका.',
      profile_title: 'प्रोफाइल',
      profile_name: 'नाव',
      profile_school: 'शाळा',
      profile_standard: 'इयत्ता',
      back: 'मागे',
      feedback_button: 'प्रतिक्रिया',
      dark_mode_label: 'डार्क मोड',
      feedback_title: 'प्रतिक्रिया पाठवा',
      feedback_placeholder: 'तुमची समस्या किंवा सूचना वर्णन करा...',
      cancel_button: 'रद्द करा',
      submit_button: 'सादर करा',
      feedback_success_title: 'प्रतिक्रिया पाठवली',
      feedback_success_msg: 'तुमच्या प्रतिसादाबद्दल धन्यवाद!',
      choose_language: 'तुमची भाषा निवडा',
      confirm_button: 'पुष्टी करा',
      onboarding_terms_error: 'तुम्ही अटी मान्य केल्या पाहिजेत.',
      standard_error: 'कृपया इयत्ता निवडा',
      onboarding_agree_terms: 'मी अटी आणि शर्तींशी सहमत आहे',
      next: 'पुढील',
      get_started: 'सुरू करा',
      back_to_edit: 'संपादित करा',
      registration_complete: 'नोंदणी पूर्ण',
      registration_success_msg: 'तुम्ही तयार आहात!',
      welcome_msg: 'परत स्वागत आहे,',
      choose_mode: 'मोड निवडा',
      extra_mode: 'एक्स्ट्रा मोड',
      extra_mode_desc: 'अतिरिक्त अभ्यास साहित्य आणि संसाधने',
      simple_mode: 'सिंपल मोड',
      simple_mode_desc: 'डायजेस्ट आणि मूलभूत नोट्स',
      ai_translator_mode: 'AI अनुवादक',
      ai_translator_desc: 'भाषाओं का त्वरित भाषांतर करा',
      theme_settings_title: 'थीम सेटिंग्ज',
      dark_mode_description: 'रात्रीच्या वेळी चांगल्या अनुभवासाठी डार्क मोड चालू करा.',
      system_theme_label: 'सिस्टमसह सिंक करा',
      system_theme_description: 'तुमच्या डिव्हाइस सेटिंग्जवर आधारित थीम स्वयंचलितपणे समायोजित करा.',
      extra_mode_title: 'एक्स्ट्रा स्टडी मोड',
      purpose_1: 'हा मोड अतिरिक्त संसाधने प्रदान करतो.',
      purpose_2: 'विषय निवडा:',
      subject_class: 'नोट्स',
      simple_mode_title: 'सिंपल स्टडी मोड',
      free_digest: 'मोफत डायजेस्ट',
      free_digest_desc: 'पूर्ण विषय डायजेस्ट मिळवा.',
      view_digest: 'डायजेस्ट पहा',
      graded_notes: 'श्रेणीकृत नोट्स',
      graded_notes_desc: 'इयत्तेनुसार आयोजित नोट्स.',
      view_pdf_notes: 'PDF नोट्स पहा',
      download_warning: 'डाउनलोड अक्षम है.',
      ai_title: 'AI अनुवादक',
      ai_source: 'पासून',
      ai_target: 'कडे',
      ai_prompt: 'मजकूर प्रविष्ट करा...',
      ai_output: 'भाषांतर',
      ai_translating: 'भाषांतर करत आहे...',
      ai_translate_btn: 'भाषांतर करा',
      ai_input_error: 'इनपुट रिकामे असू शकत नाही',
      ai_error: 'भाषांतर त्रुटी आली.',
      ai_tts_error: 'स्पीच जनरेशन अयशस्वी.',
      notes_title: 'नोट्स',
      pattern_notes: 'पॅटर्न नोट्स',
      rasagran_notes: 'रसग्रहण नोट्स',
      rasagran_basics: 'रसग्रहण मूलभूत माहिती',
      rasagran_text: 'रसग्रहणाबद्दल माहिती...',
      lesson_qna_notes: 'धडा प्रश्नोत्तर',
      lesson_qna_text: 'प्रश्न आणि उत्तरे...',
      rasagran_list_title: 'कविता',
      content_area_warning: '⚠️ हे साहित्य \'फोटो फॉरमॅट\' मध्ये आहे. कॉपी किंवा डाउनलोड करणे शक्य नाही.',
      subject_coming_soon: 'लवकरच येत आहे',
      subject_placeholder: 'या विषयासाठी नोट्स अपलोड केल्या जात आहेत.',
      digest_select_title: 'डायजेस्ट निवडा',
      pdf_select_title: 'PDF नोट निवडा',
      about_us: 'आमच्याबद्दल',
      about_app_desc: 'ज्ञान संगम हे एक सर्वसमावेशक शैक्षणिक ॲप्लिकेशन आहे जे विद्यार्थ्यांसाठी शिक्षण सुलभ करण्यासाठी डिझाइन केलेले आहे. हे डायजेस्ट, नोट्स आणि AI-साधनांमध्ये डिजिटल प्रवेश प्रदान करते.',
      version: 'आवृत्ती',
      about_simple_mode: 'सिंपल मोड: हा मोड डायजेस्ट आणि मूलभूत उजळणी नोट्स सारख्या मानक अभ्यासक्रम संसाधनांमध्ये थेट प्रवेश प्रदान करतो. दैनंदिन अभ्यास आणि जलद संदर्भासाठी आदर्श.',
      about_extra_mode: 'एक्स्ट्रा मोड: मूलभूत गोष्टींच्या पलीकडे तुमची समज वाढवण्यासाठी अतिरिक्त अभ्यास साहित्य, विषय-विशिष्ट सखोल माहिती आणि विशेष संसाधनों एक्सप्लोर करा.',
      developed_by: 'विकसित केले',
      history_btn: 'इतिहास',
      history_title: 'अनुवाद इतिहास',
      history_empty: 'अलीकडील इतिहास नाही.',
      use_this: 'वापरा',
      clear_history: 'इतिहास पुसून टाका',
  }
};

export const escapeHTML = (str: string | null | undefined): string => {
  if (!str) return '';
  return str.replace(/[&<>'"]/g, 
      tag => ({
          '&': '&amp;',
          '<': '&lt;',
          '>': '&gt;',
          "'": '&#39;',
          '"': '&quot;'
      }[tag] || tag)
  );
};

export const getLanguageDisplayName = (code: string, name: string): string => {
  return `${name}`;
};